# NumPy Arrays

In [1]:
import numpy as np

NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<b> arange </b>

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)               # 2 is the step size

array([ 0,  2,  4,  6,  8, 10])

<b> zeros and ones </b>

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

<b> linspace </b>

Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,5,20)

array([ 0.        ,  0.26315789,  0.52631579,  0.78947368,  1.05263158,
        1.31578947,  1.57894737,  1.84210526,  2.10526316,  2.36842105,
        2.63157895,  2.89473684,  3.15789474,  3.42105263,  3.68421053,
        3.94736842,  4.21052632,  4.47368421,  4.73684211,  5.        ])

Note that .linspace() includes the stop value.

<b> eye </b>

Creates an identity matrix 

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Numpy also has lots of ways to create random number arrays:

<b> rand </b>

Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1). 

In [15]:
np.random.rand(2)

array([ 0.78738835,  0.71913341])

In [16]:
np.random.rand(5,5)

array([[ 0.18867368,  0.04605814,  0.12592635,  0.25670286,  0.74412478],
       [ 0.45224415,  0.40648134,  0.30504885,  0.26752324,  0.20302487],
       [ 0.45202537,  0.21232686,  0.10298776,  0.51308893,  0.57483445],
       [ 0.13874419,  0.5756776 ,  0.03209825,  0.76070837,  0.24897533],
       [ 0.15115317,  0.04231977,  0.26697989,  0.04629011,  0.69691639]])

<b> randn </b>

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike rand which is uniform, values closer to zero are more likely to appear. 

In [18]:
np.random.randn(2)

array([-0.16495538, -0.66036824])

In [19]:
np.random.randn(5,5)

array([[ 0.60859857,  0.90405178,  1.56344071,  0.08274545,  1.66714015],
       [ 0.03675487, -0.53489266, -0.39618621,  0.10317927, -0.65203653],
       [ 0.72066086,  0.25906137,  0.74503088,  0.81158677,  1.71026356],
       [ 0.26859321, -1.3502694 , -0.12219403,  0.44754094,  0.19917438],
       [ 0.42661472,  0.23088623,  0.68231679, -0.5497697 ,  0.02982002]])

<b> randint </b>

Returns random integers from low (inclusive) to high (exclusive).

In [21]:
np.random.randint(1,100)

23

In [22]:
np.random.randint(1,100,10)

array([71, 24, 13, 58, 19, 86, 28, 53, 22, 20])

<b> seed </b>

Can be used to set the random state, so that the same "random" results can be reproduced.

In [23]:
np.random.seed(42)
np.random.rand(4)

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848])

# Array Attributes and Methods

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

# Reshape
Returns an array containing the same data with a new shape

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [29]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [30]:
ranarr.max()

39

In [31]:
ranarr.argmax()

7

In [32]:
ranarr.min()

2

In [33]:
ranarr.argmin()

9

# Shape

Shape is an attribute that arrays have (not a method):

In [34]:
# Vector
arr.shape

(25,)

In [35]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1,25).shape

(1, 25)

In [37]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [38]:
arr.reshape(25,1).shape

(25, 1)

# dtype

You can also grab the data type of the object in the array:

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# NumPy Indexing and Selection

In [41]:
#Creating sample array
arr = np.arange(0,11)

In [42]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [43]:
#Get a value at an index
arr[8]

8

In [44]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [45]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [46]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [49]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [51]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [52]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [54]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [55]:
# Getting individual element value
arr_2d[1,0]

20

In [56]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [58]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

# More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src= 'numpy_indexing.png' width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

# Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [59]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [61]:
bool_arr = arr>4

In [62]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [63]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

# Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic. Let's see some examples:

In [66]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [71]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [72]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [73]:
# Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [74]:
# Calculating exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [75]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [76]:
# Taking the Natural Logarithm
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

# Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [77]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr.sum()

45

In [79]:
arr.mean()

4.5

In [80]:
arr.max()

9

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [81]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

By passing in <tt>axis=0</tt>, we're returning an array of sums along the vertical axis, essentially <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='axis_logic.png' width=400/>

In [83]:
arr_2d.shape

(3, 4)

This tells us that <tt>arr_2d</tt> has 3 rows and 4 columns.

In <tt>arr_2d.sum(axis=0)</tt> above, the first element in each row was summed, then the second element, and so forth.

So what should <tt>arr_2d.sum(axis=1)</tt> return?

In [84]:
# THINK ABOUT WHAT THIS WILL RETURN BEFORE RUNNING THE CELL!
arr_2d.sum(axis=1)

array([10, 26, 42])